name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["CI Test Backend"]
    types:
      - completed

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-24.04
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" \
            | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-backend:${{github.sha}}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-database:${{github.sha}}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:${{github.sha}}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Trigger second repository workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.REPO_B_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/lucas-cgrs/ansible_lcongras/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}'
