name: CI Test Backend

on:
  push:
    branches:
      - develop
      - main

jobs:
  test-backend:
    name: Build and Test Backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test with Maven
        run: |
          cd simple-api
          mvn clean verify
